name: Build Laon APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cr√©ation de l'environnement Capacitor
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir www
          npx cap init Laon com.laon.app --web-dir www
          npx cap add android

      - name: Synchronisation avec Render (Live Update)
        run: |
          # Cette ligne remplace l'URL locale par ton lien Render officiel
          sed -i 's|"server": {.*}|"server": {"url": "https://apk-test.onrender.com", "cleartext": true}|' capacitor.config.json

      - name: Configuration de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilation de l'APK (Gradle)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Livraison de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Laon-Final-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
